# ------------------------------------------------------------------------------
# Mise Config
# ------------------------------------------------------------------------------
[tools]
# starship = "latest"
# zellij = "latest"
node = "latest"
pnpm = "latest"
prettier = "latest"
python = "latest"
go = "latest"
gh = "latest"
