# ------------------------------------------------------------------------------
# Mise Config
# ------------------------------------------------------------------------------
[tools]
starship = "latest"
zellij = "latest"
tmux = "latest"
neovim = "latest"
lazygit = "latest"
lazydocker = "latest"
node = "latest"
pnpm = "latest"
prettier = "latest"
python = "latest"
go = "latest"
gh = "latest"
herdr = "latest"
markdownlint-cli2 = "latest"
pi = "0.87.1"
gentle-ai = "3.6.1"
codegraph = "latest"
