# ------------------------------------------------------------------------------
# Mise Config
# ------------------------------------------------------------------------------
[tools]
starship = "latest"
zellij = "latest"
tmux = "latest"
neovim = "latest"
lazygit = "latest"
lazydocker = "latest"
node = "latest"
pnpm = "latest"
prettier = "latest"
"npm:markdownlint-cli2" = "latest"
python = "latest"
go = "latest"
gh = "latest"
herdr = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
