-- ------------------------------------------------------------------------------
-- WSL2-specific overrides
-- ------------------------------------------------------------------------------
-- This file is auto-sourced by the wsl2 init.lua (pcall dofile). It carries
-- per-env settings that do not belong in the shared `lua/config/*.lua` files
-- (which are canonical = omarchy).
--
-- When adding new shared-level settings, edit `shared/nvim/lua/config/*.lua`
-- instead. Use THIS file only for true wsl2-only deltas.

-- Spell config moved to shared/nvim/lua/config/options.lua
