general {
    gaps_in        = 2
    gaps_out       = 4
    border_size    = 2
    layout         = dwindle
}

decoration {
    rounding       = 6
    dim_inactive   = false
    dim_strength   = 0.15
}

animations {
    enabled        = true
}

layout {
    single_window_aspect_ratio = -1 -1
}

scrolling {
    column_width   = 0.5
}
