windowrule = float on, center 1, size 1152 648, match:class org.gnome.Nautilus
windowrule = float on, match:class org.gnome.Calculator

windowrule = float on, center 1, size 1152 648, match:class ^chrome-www\.netflix\.com__-Default$
windowrule = float on, center 1, size 1152 648, match:class ^chrome-web\.whatsapp\.com__-Default$
windowrule = float on, center 1, size 1152 648, match:class ^chrome-www\.youtube\.com__-Default$
