# ------------------------------------------------------------------------------
# Mise Config
# ------------------------------------------------------------------------------
[tools]
# Omarchy Default
codex = "latest"
go = "latest"
node = "26.7.0"
opencode = "latest"
pi = "latest"
python = "latest"

# Custom
"npm:markdownlint-cli2" = "latest"
pnpm = "latest"
prettier = "latest"
zellij = "latest"
