# ------------------------------------------------------------------------------
# Mise Config
# ------------------------------------------------------------------------------
[tools]
# Omarchy Default
codex = "latest"
go = "latest"
node = "latest"
opencode = "latest"
pnpm = "latest"
prettier = "latest"
zellij = "latest"
gh = "latest"
pi = "latest"
markdownlint-cli2 = "latest"
herdr = "latest"
gentle-ai = "latest"
codegraph = "latest"

[settings.upgrade]
auto_prune = false
