# ------------------------------------------------------------------------------
# Mise Config
# ------------------------------------------------------------------------------
[tools]
go = "latest"
node = "latest"
"npm:markdownlint-cli2" = "latest"
pnpm = "latest"
prettier = "latest"
python = "latest"
zellij = "latest"
